// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvoekkcftbbiefkgcqae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2b2Vra2NmdGJiaWVma2djcWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NDUxMTUsImV4cCI6MjA2MDAyMTExNX0.4Lz2Gdm2zq9sc8r6pPsN-xqUwph0w_wmQlVBRO-UvdA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);